### ISSUE TITLE
Fix import path in "htmlComponents/baseComponent.vue" 

### ISSUE THREAD

**Issue by davoreric** [trikoder/trim#12]
Please set relative path for importing "dialogModal", since currently it relies on having "trim" alias set up in Webpack.

CURRENT
`import {confirm} from 'trim/components/dialogModal';`

REQUESTED
`import {confirm} from '../../components/dialogModal';`

https://github.com/trikoder/trim/blob/master/src/js/formElements/htmlComponents/baseComponent.vue#L3

**Comment by dbrekalo** [comment]
@davoreric fixed in version 0.79.1
